CREATE DATABASE IF NOT EXISTS EJERCICIO_NUAAV;

USE DATABASE EJERCICIO_NUAAV;
USE WAREHOUSE COMPUTE_WH;

CREATE SCHEMA IF NOT EXISTS EJERCICIO_NUAAV.RAW;
CREATE SCHEMA IF NOT EXISTS EJERCICIO_NUAAV.STAGING;
CREATE SCHEMA IF NOT EXISTS EJERCICIO_NUAAV.CANONICAL;

CREATE STAGE IF NOT EXISTS EJERCICIO_NUAAV.RAW.SRC_FILES;

CREATE OR REPLACE FILE FORMAT EJERCICIO_NUAAV.RAW.FF_RAW_LINES
  TYPE = CSV
  FIELD_DELIMITER = '\u0002'
  RECORD_DELIMITER = '\n'
  SKIP_HEADER = 0
  TRIM_SPACE = FALSE
  FIELD_OPTIONALLY_ENCLOSED_BY = NONE
  ESCAPE_UNENCLOSED_FIELD = NONE;

CREATE OR REPLACE FILE FORMAT EJERCICIO_NUAAV.RAW.FF_XML
  TYPE = XML;