USE DATABASE EJERCICIO_NUAAV;

-- 1. Conteo por capa: nada se pierde sin registro
SELECT 'RAW lines'        AS capa, COUNT(*) AS filas FROM EJERCICIO_NUAAV.RAW.RAW_FILE_LINES
UNION ALL SELECT 'XML transactions', COUNT(*) FROM EJERCICIO_NUAAV.STAGING.V_XML_TRANSACTIONS
UNION ALL SELECT 'JSON transactions', COUNT(*) FROM EJERCICIO_NUAAV.STAGING.V_JSON_TRANSACTIONS
UNION ALL SELECT 'FACT_ORDER', COUNT(*) FROM EJERCICIO_NUAAV.CANONICAL.FACT_ORDER
UNION ALL SELECT 'FACT_ORDER_ITEM', COUNT(*) FROM EJERCICIO_NUAAV.CANONICAL.FACT_ORDER_ITEM
UNION ALL SELECT 'FACT_PAYMENT', COUNT(*) FROM EJERCICIO_NUAAV.CANONICAL.FACT_PAYMENT
UNION ALL SELECT 'REJECTS', COUNT(*) FROM EJERCICIO_NUAAV.CANONICAL.REJECTS;


-- 2. Integridad referencial: ningun hecho apunta a una dimension inexistente
SELECT 'orders_sin_customer' AS check_name, COUNT(*) AS violaciones
FROM EJERCICIO_NUAAV.CANONICAL.FACT_ORDER o
LEFT JOIN EJERCICIO_NUAAV.CANONICAL.DIM_CUSTOMER c ON c.customer_key = o.customer_key
WHERE o.customer_key IS NOT NULL AND c.customer_key IS NULL

UNION ALL

SELECT 'items_sin_order', COUNT(*)
FROM EJERCICIO_NUAAV.CANONICAL.FACT_ORDER_ITEM i
LEFT JOIN EJERCICIO_NUAAV.CANONICAL.FACT_ORDER o ON o.order_key = i.order_key
WHERE o.order_key IS NULL

UNION ALL

SELECT 'items_sin_product', COUNT(*)
FROM EJERCICIO_NUAAV.CANONICAL.FACT_ORDER_ITEM i
LEFT JOIN EJERCICIO_NUAAV.CANONICAL.DIM_PRODUCT p ON p.product_key = i.product_key
WHERE p.product_key IS NULL

UNION ALL

SELECT 'payments_sin_order', COUNT(*)
FROM EJERCICIO_NUAAV.CANONICAL.FACT_PAYMENT p
LEFT JOIN EJERCICIO_NUAAV.CANONICAL.FACT_ORDER o ON o.order_key = p.order_key
WHERE o.order_key IS NULL;


-- 3. Unicidad de claves naturales por sistema fuente
SELECT 'dup_customer' AS check_name, COUNT(*) AS violaciones FROM (
  SELECT source_system, source_customer_id
  FROM EJERCICIO_NUAAV.CANONICAL.DIM_CUSTOMER
  GROUP BY 1,2 HAVING COUNT(*) > 1
)
UNION ALL
SELECT 'dup_product', COUNT(*) FROM (
  SELECT source_system, sku
  FROM EJERCICIO_NUAAV.CANONICAL.DIM_PRODUCT
  GROUP BY 1,2 HAVING COUNT(*) > 1
)
UNION ALL
SELECT 'dup_order', COUNT(*) FROM (
  SELECT source_system, source_order_id
  FROM EJERCICIO_NUAAV.CANONICAL.FACT_ORDER
  GROUP BY 1,2 HAVING COUNT(*) > 1
);
